sudo: false
language: go
go: '1.11'
notifications:
  email:
    on_success: never
    on_failure: never
git:
  depth: 5
before_deploy:
- sha256sum m3rger* > checksums.sha256
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: P+Rncrwu7uTco+vbG2lI29GFbLe9CZkEQK/4aHPqD0lzdgR02TJf5j+d35cNyav4KNwOKxea6HyCBA88KzZ+t3n8TQ0N3aGA2ugLXkynUees18HZ7c1ARD50uc1IjhXEFBUHuULp/BzPa8x/4Keg1E9SPRwawuBJmoWkbMyI0jv0aVTFda7Cv7MR4hIyu4GqUWb1yl2SldB+kjgoufg9sItSImJosEpn+b+uAZUXF/LouW2fSYGDL0HYhoe4vWtsssGDEb+CbWORnGjvGcVZdFlDNA7wPxKVEJ4ejlNtZcjpVoxriwu6MImMygL7ZJwXrNcNqhorA5pgmZjPAhqA1eqUhq16NI1KGl9v0gRLlSxWg9r0F2TWoNPGhubTmM7eZNBn7RVgYmBzQPHkTdfKJJmiedzfzmieGRdbLWwwkgdhhupniCZPSD2xzKJ4lAClY6KqFu4sAAQUM9gfD+2wJQ2mQNCu5xthgQMtDGjJohtp23uQRXeRqmH7eaMBGqBE5wG4YMzJLRFM/ZdUoY7wVz/2l3IhgHv5N9olfNA38FV6YzzmiAqd/xAqi7qzc4hNgQkk+RxER2vthfV4WoTEbMJSpChovOksXwS33H8bPqFUiiZxcaaKkmeJFFMufi0PtIdF5h1HSlFmOQ8CIlTZSHSqQ+L/cZY1UBT24Jgy1N4=
  file:
  - m3rger-linux
  - m3rger-darwin
  - m3rger-windows.exe
  - checksums.sha256
  on:
    tags: true
    repo: benjdewan/m3rger
