sudo: false
language: go
go: 1.10
notifications:
  email:
    on_success: never
    on_failure: never
git:
  depth: 5
before_deploy:
- sha256sum m3rger* > checksums.sha256
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fAqdhD3UVqY3n+k60zNYuSWm647g3TmRF3+b7/dWKijEg+Vqekyrvxs7udSYkFbib0noLhZq2evSurFB77SB/988wVqkcLgRDjDfOglH+MfS3q1LDYWJbO8Ylx3WKjr5tQ0IVbJi6wrj1hShEe2/c1hChxLgevMIBCMUE+ubWS2g24OzDIpb4zefhUplUyHF8zPRuFHg3/h/wYxUa8tmR0+AIOHARRNEMr2j5C+0KZfRhvMCz0W2OgvHrmkt08JOM6IYVnkmjeUcgIWV5Mih0wOhcTo1CiLUZM0NITT1m9VwqfMBiRLSWDVpTLlou0rALBN+fEskIHDEd5EjVHHySkbQi5aM6iXFqQ0pm6FDDHARyeZqLyXiHjVI4bNW0hAcQmDfzYRGsVKf2oKunXg1EzgINy8UrlRV9CuD73wUZzxFQz04Z4ZMifxd5n7VD7G8smKrgiHP+UaeRURAVIZNt+qZDGvuVz6fdwjtEE99oDUssTQTwa3LkV9oTWzAncu7cJpMYfx/G7JFt4bPA4wFwx+0s7mytH0hN5hQAANTtLFvMHI63j2th+SJzVpRE8u3FVaNMa1q9mfaZ+wq7JWxDPOGxFVpuMho/El4wHuIrehVAzWSE0Av23RnFQnFNokahPjSrmx3onsgUZGbbhq/qQDR1KmGrhoM9KLaNXBGSig=
  file:
      - m3rger-linux
      - m3rger-darwin
      - m3rger-windows.exe
      - checksums.sha256
  on:
    tags: true
    repo: benjdewan/m3rger
